spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service
                fallbackuri: forward:/authFallBack
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallBack
        - id: benefit-service
          uri: lb://BENEFIT-SERVICE
          predicates:
            - Path=/benefit-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: benefit-service
                fallbackuri: forward:/benefitFallBack

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000