server:
  port: 9000

com.pot:
  auth:
    client:
      clientId: client
      secret: secret
    jks-file:
      name: jwt.jks
      password: 123456
    token-timings:
      accessTokenValiditySeconds: 3600000
      refreshTokenValiditySeconds: 86400
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_app
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        default_schema: public
    show-sql: true
  application:
    name: AUTH-SERVICE