package com.pot.common.enums;

public enum FunctionName {
  COMPANY_MANAGER,
  COMPANY_CLAIM_MANAGER,
  COMPANY_SETTING_MANAGER,
  COMPANY_REPORT_MANAGER,
  CONSUMER,
  CONSUMER_CLAIM_MANAGER,
  SUPER_ADMIN
}
